version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes  # Enable AOF persistence
    volumes:
      - redis-data:/data  # Mount a volume for data persistence

  rust-app:
    build: ./rust-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - RUN_MODE=app
    command: ./target/release/rust-app

  rust-worker:
    build: ./rust-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - RUN_MODE=worker
    command: ./target/release/rust-app
    deploy:
      mode: replicated
      replicas: 1  # Run multiple instances of the worker
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
volumes:
  redis-data:  # Define the volume