version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rust-app:
    build: ./rust-app
    container_name: rust-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ./target/release/rust-app