[package]
name = "celerylib"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
redis = "0.31"
thiserror = "2.0.12"
uuid = { version = "1.16", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
